# Generated by Django 4.2.8 on 2023-12-20 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCareapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=75)),
                ('doc_post', models.CharField(max_length=255)),
                ('doc_timming', models.CharField(max_length=19)),
                ('doc_ranking', models.FloatField(max_length=3)),
                ('doc_room', models.IntegerField()),
                ('doc_specialization', models.CharField(max_length=100)),
                ('phone_number', models.PositiveIntegerField()),
                ('doc_email_address', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('doc_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthCareapp.adddepartment')),
            ],
        ),
        migrations.AddField(
            model_name='makeappointment',
            name='created',
            field=models.DateTimeField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='makeappointment',
            name='description',
            field=models.CharField(default=123, max_length=800),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='makeappointment',
            name='email_address',
            field=models.EmailField(default=123, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='Address',
            field=models.CharField(default=123, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='city',
            field=models.CharField(default=123, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='state',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='makeappointment',
            name='Disease',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_write', models.CharField(max_length=500)),
                ('review_star', models.FloatField()),
                ('appoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthCareapp.makeappointment')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthCareapp.doctors')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthCareapp.signup')),
            ],
        ),
        migrations.CreateModel(
            name='ChatsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usermsg', models.CharField(max_length=1000)),
                ('botmsg', models.CharField(max_length=500)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthCareapp.signup')),
            ],
        ),
        migrations.AlterField(
            model_name='makeappointment',
            name='Doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthCareapp.doctors'),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthCareapp.doctors'),
        ),
        migrations.DeleteModel(
            name='Doctors',
        ),
    ]
